spring:
  application:
    name: dubbo-consumer
  dubbo:
    registry: zookeeper://192.168.0.84:2181
    #registry: zookeeper://192.168.56.101:2181
    #registry: zookeeper://localhost:2181
    check: false
    timeout: 500000
    protocol:
      name: dubbo
      port: 33261
server:
  port: 8083